allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - astro@7.2.9
  - '@mui/core-downloads-tracker@9.4.0'
  - '@mui/material@9.4.0'
  - '@mui/private-theming@9.4.0'
  - '@mui/styled-engine@9.4.0'
  - '@mui/system@9.4.0'
  - '@mui/types@9.4.0'
  - '@mui/utils@9.4.0'
